#define SETBIT(WORD,BIT) WORD|=1<<BIT
#define CLRBIT(WORD,BIT) WORD&=~(1<<BIT)
#define READBIT(WORD,BIT) ((WORD>>BIT)&1)

#define WRITEBIT(WORD,BIT,BITLEVEL) (BITLEVEL?(WORD|=1<<BIT):(WORD&=~(1<<BIT)))

#define READWRITEBIT(DWORD,DBIT,SWORD,SBIT) DWORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))

#define WRITE2PORTBIT(PORTNO,BITPOS,BITLEVEL) ((PORTNO==0)?\
(BITLEVEL?(IOSET0=1<<BITPOS):(IOCLR0=1<<BITPOS)):(BITLEVEL?(IOSET1=1<<BITPOS):(IOCLR1=1<<BITPOS)))

#define WRITEBYTE(WORD,BITSTARTPOS,BYTE) WORD=((WORD&~(0XFF<<BITSTARTPOS))|(BYTE<<BITSTARTPOS))

#define READNIBBLE(WORD,NIBBLEPOS) ((WORD>>NIBBLEPOS)&0x0f)

#define WRITENIBBLE(WORD,NIBBLEPOS,NIBBLE) WORD=((WORD&~(0x0F<<NIBBLEPOS))|(NIBBLE<<NIBBLEPOS))

#define OLED_PIN 5

#define OBUZ_PIN 4
